<footer>
        <h3>Contactez-nous</h3>
        <p>Email : <a href="mailto:LaPlumeDigitale2.0@gmail.com">LaPlumeDigitale2.0@gmail.com</a></p>
        <p>Téléphone : 01 02 03 04 05</p>
        <a href="index.php?action=contact">Politique de confidentialité</a><br>
        <p>Suivez-nous sur nos réseaux sociaux :</p>
        <ul class="social-links">
            <a href="https://www.x.com"> <img src="img/logo-twitter.png" target="_blank" alt="X"> </a>
            <a href="https://www.youtube.com/channel/UCGj23Uzjs6V01XPg2wyt5dQ"> <img src="img/logo-youtube.png" target="_blank" alt="Youtube"> </a>
            <a href="https://www.Instagram.com"> <img src="img/logo-instagram.png" target="_blank" alt="Instagram"> </a>
            <a href="https://discord.gg/H6bP228n"> <img src="img/logo-discord.png" target="_blank" alt="Discord"> </a>
        </ul>
    </footer>
</body>
</html>
